import './globals.css'
import { Suspense } from 'react'

import { Open_Sans } from 'next/font/google'

import { MainLoader } from '@/components/ui/main-loader'
import { ThemeProvider } from '@/components/ui/theme-provider'
import { Toaster } from '@/components/ui/toaster'
import AuthContext from '@/context/AuthContext'
import { cn } from '@/lib/utils'

import type { Metadata } from 'next'


const font = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang='en'>
      <body className={cn(font.className)}>
        <Suspense fallback={<MainLoader />}>
          <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
            <AuthContext>{children}</AuthContext>
          </ThemeProvider>
          <Toaster />
        </Suspense>
      </body>
    </html>
  )
}
